name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup NodeJS Environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build Frontend
      run: bash ./build/frontend.sh

    - name: Build backend
      run: bash ./build/backend.sh
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist
